import Link from "next/link";
import { getPublishedHomepage } from "@/lib/homepageService";
import { DynamicPricingCard } from "@/components/pricing/DynamicPricingCard";
import { AppIcon, type AppIconName } from "@/components/ui/AppIcon";

const featureIcons: AppIconName[] = ["spark","planner","wallet","career","scholarship","life"];
const publicLinks = [["/students","Students"],["/international-students","International students"],["/universities","Universities"],["/student-discounts","Discounts"],["/student-money","Student money"],["/pricing","Pricing"],["/support","Support"]];

export default async function HomePage(){
  const {homepage,metrics,ready}=await getPublishedHomepage();
  if(!ready||!homepage){return <main className="ui-page"><section className="ui-container flex min-h-screen items-center justify-center"><div className="ui-card max-w-xl text-center"><span className="ui-icon-tile mx-auto"><AppIcon name="coursework" className="h-5 w-5"/></span><h1 className="mt-5 text-3xl font-black">Homepage content is being prepared</h1><p className="mt-3 leading-7 text-slate-600">Publish the homepage content record in the administration area to activate the public experience.</p><Link href="/login/admin" className="ui-button mt-6">Open administration</Link></div></section></main>}
  return <main className="ui-page">
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-5 px-4 py-4 sm:px-6 lg:px-8"><nav className="hidden items-center gap-1 lg:flex">{publicLinks.map(([href,label])=><Link key={href} href={href} className="rounded-lg px-3 py-2 text-sm font-bold text-slate-600 transition hover:bg-white hover:text-slate-950">{label}</Link>)}</nav><div className="ml-auto flex items-center gap-2"><Link href="/search" className="ui-button-secondary h-11 w-11 p-0" aria-label="Search"><AppIcon name="search" className="h-4 w-4"/></Link><Link href="/login" className="ui-button-secondary">Log in</Link><Link href="/register" className="ui-button">Get started</Link></div></div></header>

    <section className="mx-auto grid max-w-[1440px] gap-10 px-4 pb-20 pt-14 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:pt-20"><div><span className="ui-badge"><AppIcon name="spark" className="h-4 w-4"/>Student life, organised</span><h1 className="mt-7 max-w-3xl text-5xl font-black tracking-[-.055em] text-slate-950 sm:text-6xl lg:text-7xl">{homepage.heroHeadline}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{homepage.heroSubheadline}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={homepage.primaryCtaHref} className="ui-button">{homepage.primaryCtaLabel}<AppIcon name="arrow" className="h-4 w-4"/></Link>{homepage.secondaryCtaHref&&homepage.secondaryCtaLabel&&<Link href={homepage.secondaryCtaHref} className="ui-button-secondary">{homepage.secondaryCtaLabel}</Link>}</div><div className="mt-8 flex flex-wrap items-center gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><AppIcon name="check" className="h-4 w-4 text-green-600"/>Free account setup</span><span className="flex items-center gap-2"><AppIcon name="shield" className="h-4 w-4 text-indigo-600"/>Private by design</span></div></div>
      <div className="rounded-[30px] border border-slate-200 bg-white p-4 sm:p-6"><div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-[0_18px_60px_rgba(15,23,42,.08)]"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-sm font-extrabold">Good morning</p><p className="mt-1 text-xs text-slate-500">Here is your student day at a glance.</p></div><span className="ui-icon-tile"><AppIcon name="bell" className="h-4 w-4"/></span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="ui-stat"><AppIcon name="calendar" className="h-5 w-5 text-indigo-600"/><p className="mt-4 text-xs font-bold text-slate-500">Classes today</p><p className="mt-1 text-2xl font-black">3</p></div><div className="ui-stat"><AppIcon name="coursework" className="h-5 w-5 text-green-600"/><p className="mt-4 text-xs font-bold text-slate-500">Tasks due</p><p className="mt-1 text-2xl font-black">5</p></div><div className="ui-stat"><AppIcon name="wallet" className="h-5 w-5 text-orange-600"/><p className="mt-4 text-xs font-bold text-slate-500">Weekly budget</p><p className="mt-1 text-2xl font-black">On track</p></div></div><div className="mt-4 grid gap-4 sm:grid-cols-[1.2fr_.8fr]"><div className="ui-card-soft"><div className="flex items-center justify-between"><b>Today&apos;s plan</b><span className="text-xs font-bold text-indigo-600">View planner</span></div><div className="mt-4 grid gap-3">{["Review lecture notes","Submit coursework","Focus session"].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-white p-3"><span className="inline-flex h-7 w-7 items-center justify-center rounded-lg border border-slate-200 text-xs font-black text-indigo-600">{i+1}</span><span className="text-sm font-bold">{x}</span></div>)}</div></div><div className="ui-card-soft"><b>AI study assistant</b><p className="mt-3 text-sm leading-6 text-slate-600">Explain a difficult topic, structure revision or turn notes into a study plan.</p><div className="mt-4 flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 text-xs text-slate-400">Ask a study question<AppIcon name="arrow" className="ml-auto h-4 w-4 text-indigo-600"/></div></div></div></div></div>
    </section>

    {metrics.length>0&&<section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-[1440px] divide-y divide-slate-200 px-4 sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-6 lg:px-8">{metrics.map(metric=><article key={metric.id} className="px-6 py-8 text-center"><p className="text-3xl font-black tracking-tight">{metric.value}</p><p className="mt-2 text-sm font-bold text-slate-500">{metric.label}</p></article>)}</div></section>}

    <section className="mx-auto max-w-[1440px] px-4 py-20 sm:px-6 lg:px-8"><div className="text-center"><p className="ui-eyebrow">One student operating system</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">All the tools you need to move forward</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-600">A calm, connected workspace for academic progress, money, opportunities and everyday university life.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{homepage.sections.map((section,index)=><article key={section.id} className="ui-card group"><span className="ui-icon-tile"><AppIcon name={featureIcons[index%featureIcons.length]} className="h-5 w-5"/></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.16em] text-indigo-600">{section.sectionType}</p><h3 className="mt-2 text-2xl font-black tracking-tight">{section.title}</h3><p className="mt-3 leading-7 text-slate-600">{section.body}</p>{section.ctaHref&&section.ctaLabel&&<Link href={section.ctaHref} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-indigo-600">{section.ctaLabel}<AppIcon name="arrow" className="h-4 w-4"/></Link>}</article>)}</div></section>

    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-[1440px] px-4 py-20 sm:px-6 lg:px-8"><div className="text-center"><p className="ui-eyebrow">Simple setup</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Start in three clear steps</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["users","Create your account","Register securely and confirm your student profile."],["settings","Personalise the experience","Choose your country, study goals and preferences."],["arrow","Move through university with clarity","Use one dashboard to plan, save and grow."]].map(([icon,title,body],i)=><article key={title} className="ui-card"><span className="ui-icon-tile"><AppIcon name={icon as AppIconName} className="h-5 w-5"/></span><p className="mt-5 text-xs font-black text-indigo-600">0{i+1}</p><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-slate-600">{body}</p></article>)}</div></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-8 px-4 py-20 sm:px-6 lg:grid-cols-[1fr_.8fr] lg:items-start lg:px-8"><div><p className="ui-eyebrow">Flexible access</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Start free, upgrade when it adds value</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">Transparent, localised pricing designed around student needs.</p></div><DynamicPricingCard/></section>

    <section className="mx-auto max-w-[1440px] px-4 pb-20 sm:px-6 lg:px-8"><div className="rounded-[28px] border border-indigo-100 bg-indigo-50 p-8 sm:p-12"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="ui-eyebrow">Ready when you are</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Make university life feel more manageable.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Create your account and build a student workspace around your real goals.</p></div><Link href="/register" className="ui-button shrink-0">Get started<AppIcon name="arrow" className="h-4 w-4"/></Link></div></div></section>

    <footer className="border-t border-slate-200"><div className="mx-auto grid max-w-[1440px] gap-8 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8"><div><p className="text-sm font-black">Student operating system</p><p className="mt-3 max-w-xs text-sm leading-6 text-slate-500">A modern workspace for study, money, career and student life.</p></div>{[["Students",["Academic assistant","Planner","Wallet","Wellbeing"]],["Explore",["International students","Scholarships","Marketplace","Discounts"]],["Support",["Help centre","Safety","Privacy","Accessibility"]]].map(([title,links])=><div key={title as string}><p className="text-sm font-black">{title as string}</p><div className="mt-3 grid gap-2">{(links as string[]).map(x=><span key={x} className="text-sm text-slate-500">{x}</span>)}</div></div>)}</div><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-4 py-6 text-xs text-slate-500 sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} All rights reserved.</span><div className="flex gap-5"><span>Privacy</span><span>Terms</span><span>Cookies</span></div></div></footer>
  </main>
}
