import Stripe from "stripe";
import { prisma } from "@/lib/prisma";
function client(){ const key=process.env.STRIPE_SECRET_KEY; if(!key) throw new Error("STRIPE_NOT_CONFIGURED"); return new Stripe(key); }
export async function createSubscriptionCheckout(input:{userId:string;priceId:string;successUrl:string;cancelUrl:string;customerEmail?:string}){ return client().checkout.sessions.create({mode:"subscription",line_items:[{price:input.priceId,quantity:1}],success_url:input.successUrl,cancel_url:input.cancelUrl,customer_email:input.customerEmail,metadata:{userId:input.userId}}); }
export async function createMarketplacePaymentIntent(input:{orderId:string;amountCents:number;currencyCode:string;platformFeeCents?:number;connectedAccountId?:string}){ return client().paymentIntents.create({amount:input.amountCents,currency:input.currencyCode.toLowerCase(),automatic_payment_methods:{enabled:true},metadata:{orderId:input.orderId},...(input.connectedAccountId?{application_fee_amount:input.platformFeeCents||0,transfer_data:{destination:input.connectedAccountId}}:{})}); }
export async function refundMarketplacePayment(input:{orderId:string;paymentIntentId:string;amountCents?:number;reason?:string}){ return client().refunds.create({payment_intent:input.paymentIntentId,...(input.amountCents?{amount:input.amountCents}:{}),metadata:{orderId:input.orderId,reason:input.reason||"REQUESTED_BY_CUSTOMER"}}); }
export async function verifyStripeWebhook(rawBody:string,signature:string){ const secret=process.env.STRIPE_WEBHOOK_SECRET; if(!secret) throw new Error("STRIPE_WEBHOOK_NOT_CONFIGURED"); return client().webhooks.constructEvent(rawBody,signature,secret); }
export async function applyStripeEvent(event:Stripe.Event){
 if(event.type==="checkout.session.completed"){ const s=event.data.object as Stripe.Checkout.Session; const userId=s.metadata?.userId; if(userId&&s.subscription){ const existing=await prisma.subscriptionEntitlement.findFirst({where:{userId}}); if(existing){ await prisma.subscriptionEntitlement.update({where:{id:existing.id},data:{status:"ACTIVE",stripeSubscriptionId:String(s.subscription)}}); }else{ await prisma.subscriptionEntitlement.create({data:{userId,status:"ACTIVE",stripeSubscriptionId:String(s.subscription),planCode:"premium",billingPeriod:"monthly",countryCode:"GB",currencyCode:"GBP"}}); } }}
 if(event.type==="customer.subscription.deleted"){ const s=event.data.object as Stripe.Subscription; const existing=await prisma.subscriptionEntitlement.findFirst({where:{stripeSubscriptionId:s.id}}); if(existing){ await prisma.subscriptionEntitlement.update({where:{id:existing.id},data:{status:"CANCELLED"}}); } }
 if(event.type==="payment_intent.succeeded"){ const i=event.data.object as Stripe.PaymentIntent; const orderId=i.metadata?.orderId; if(orderId) await prisma.marketplaceOrder.updateMany({where:{id:orderId},data:{paymentStatus:"PAID"}}); }
 return {processed:true,type:event.type};
}
