"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { LogoutButton } from "@/components/auth/LogoutButton";
import { AppIcon, type AppIconName } from "@/components/ui/AppIcon";
const groups:Array<[string,Array<[string,string,AppIconName]>]>=[
 ["Operations",[["/admin","Overview","home"],["/admin/users","Users","users"],["/admin/support","Support","support"],["/admin/notifications","Notifications","bell"],["/admin/moderation","Moderation","shield"]]],
 ["Business",[["/admin/finance","Finance","finance"],["/admin/analytics","Analytics","chart"],["/admin/content","Content","coursework"],["/admin/pricing","Pricing","budget"]]],
 ["Platform",[["/admin/feature-flags","Feature flags","flag"],["/admin/monitoring","Monitoring","chart"],["/admin/jobs","Background jobs","jobs"],["/admin/operations","Operational paths","jobs"],["/admin/audit","Audit trail","shield"]]],
];
export function AdminSidebar(){const pathname=usePathname();return <aside className="admin-sidebar lg:sticky lg:top-4 lg:h-[calc(100vh-2rem)]"><nav className="flex h-full gap-2 overflow-x-auto rounded-[22px] border border-sky-100 bg-white p-3 shadow-[0_16px_48px_rgba(2,132,199,.08)] lg:flex-col lg:overflow-y-auto"><div className="hidden border-b border-sky-50 px-3 pb-5 pt-2 lg:block"><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">Administration</p><h2 className="mt-2 text-xl font-black">Platform operations</h2><p className="mt-1 text-xs leading-5 text-slate-500">Users, safety, content, finance and service health.</p></div><div className="flex gap-2 lg:grid">{groups.map(([title,items])=><div key={title} className="grid gap-1"><p className="px-3 pb-1 pt-3 text-[10px] font-black uppercase tracking-[.18em] text-slate-400">{title}</p>{items.map(([href,label,icon])=>{const active=pathname===href||(href!=="/admin"&&pathname.startsWith(href));return <Link key={href} href={href} className={`group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold ${active?"bg-sky-600 text-white":"text-slate-600 hover:bg-sky-50 hover:text-sky-900"}`}><span className={`inline-flex h-8 w-8 items-center justify-center rounded-lg border ${active?"border-white/20 bg-white/10":"border-slate-200 bg-white text-slate-500"}`}><AppIcon name={icon} className="h-4 w-4"/></span>{label}</Link>})}</div>)}</div><div className="ml-auto shrink-0 lg:mt-auto lg:ml-0"><LogoutButton/></div></nav></aside>}
